---
abstract: 'perl implementation of Locality Sensitive Hashing'
author:
  - 'Takeshi Miki <miki@cpan.org>'
build_requires:
  FindBin::libs: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-LSH
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Filter::Util::Call: 0
  List::MoreUtils: 0
  List::Util: 0
  Scalar::Util: 0
  Storable: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00001_01
